# Generated by Django 4.2.20 on 2025-04-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0002_disponibilidadehorarios_reuniao'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorados',
            name='token',
            field=models.CharField(default=52, max_length=16),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Reuniao',
        ),
    ]
